package com.ml.cxrules.pagos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Payment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String user_status;
   private java.lang.String cart;
   private java.lang.String operation_type;
   private java.lang.String buy_equals_pay;
   private java.lang.String payment_status;
   private java.lang.String payment_type;
   private java.util.List<java.lang.Integer> contents;

   private java.lang.String site;

   private java.lang.String payment_method_id;

   public Payment()
   {
   }

   public java.lang.String getUser_status()
   {
      return this.user_status;
   }

   public void setUser_status(java.lang.String user_status)
   {
      this.user_status = user_status;
   }

   public java.lang.String getCart()
   {
      return this.cart;
   }

   public void setCart(java.lang.String cart)
   {
      this.cart = cart;
   }

   public java.lang.String getOperation_type()
   {
      return this.operation_type;
   }

   public void setOperation_type(java.lang.String operation_type)
   {
      this.operation_type = operation_type;
   }

   public java.lang.String getBuy_equals_pay()
   {
      return this.buy_equals_pay;
   }

   public void setBuy_equals_pay(java.lang.String buy_equals_pay)
   {
      this.buy_equals_pay = buy_equals_pay;
   }

   public java.lang.String getPayment_status()
   {
      return this.payment_status;
   }

   public void setPayment_status(java.lang.String payment_status)
   {
      this.payment_status = payment_status;
   }

   public java.lang.String getPayment_type()
   {
      return this.payment_type;
   }

   public void setPayment_type(java.lang.String payment_type)
   {
      this.payment_type = payment_type;
   }

   public java.util.List<java.lang.Integer> getContents()
   {
      return this.contents;
   }

   public void setContents(java.util.List<java.lang.Integer> contents)
   {
      this.contents = contents;
   }

   public java.lang.String getSite()
   {
      return this.site;
   }

   public void setSite(java.lang.String site)
   {
      this.site = site;
   }

   public java.lang.String getPayment_method_id()
   {
      return this.payment_method_id;
   }

   public void setPayment_method_id(java.lang.String payment_method_id)
   {
      this.payment_method_id = payment_method_id;
   }

   public Payment(java.lang.String user_status, java.lang.String cart,
         java.lang.String operation_type, java.lang.String buy_equals_pay,
         java.lang.String payment_status, java.lang.String payment_type,
         java.util.List<java.lang.Integer> contents, java.lang.String site,
         java.lang.String payment_method_id)
   {
      this.user_status = user_status;
      this.cart = cart;
      this.operation_type = operation_type;
      this.buy_equals_pay = buy_equals_pay;
      this.payment_status = payment_status;
      this.payment_type = payment_type;
      this.contents = contents;
      this.site = site;
      this.payment_method_id = payment_method_id;
   }

}