package com.ml.cxrules.envios;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Shipment implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String user_status;
   private java.lang.String cart;
   private java.lang.String operation_type;
   private java.lang.String buy_equals_pay;
   private java.lang.String shipping_status;
   private java.lang.String open_claim;
   private java.lang.String me;

   private java.lang.String site;

   private java.util.List<java.lang.Long> contents;

   public Shipment()
   {
   }

   public java.lang.String getUser_status()
   {
      return this.user_status;
   }

   public void setUser_status(java.lang.String user_status)
   {
      this.user_status = user_status;
   }

   public java.lang.String getCart()
   {
      return this.cart;
   }

   public void setCart(java.lang.String cart)
   {
      this.cart = cart;
   }

   public java.lang.String getOperation_type()
   {
      return this.operation_type;
   }

   public void setOperation_type(java.lang.String operation_type)
   {
      this.operation_type = operation_type;
   }

   public java.lang.String getBuy_equals_pay()
   {
      return this.buy_equals_pay;
   }

   public void setBuy_equals_pay(java.lang.String buy_equals_pay)
   {
      this.buy_equals_pay = buy_equals_pay;
   }

   public java.lang.String getShipping_status()
   {
      return this.shipping_status;
   }

   public void setShipping_status(java.lang.String shipping_status)
   {
      this.shipping_status = shipping_status;
   }

   public java.lang.String getOpen_claim()
   {
      return this.open_claim;
   }

   public void setOpen_claim(java.lang.String open_claim)
   {
      this.open_claim = open_claim;
   }

   public java.lang.String getMe()
   {
      return this.me;
   }

   public void setMe(java.lang.String me)
   {
      this.me = me;
   }

   public java.lang.String getSite()
   {
      return this.site;
   }

   public void setSite(java.lang.String site)
   {
      this.site = site;
   }

   public java.util.List<java.lang.Long> getContents()
   {
      return this.contents;
   }

   public void setContents(java.util.List<java.lang.Long> contents)
   {
      this.contents = contents;
   }

   public Shipment(java.lang.String user_status, java.lang.String cart,
         java.lang.String operation_type, java.lang.String buy_equals_pay,
         java.lang.String shipping_status, java.lang.String open_claim,
         java.lang.String me, java.lang.String site,
         java.util.List<java.lang.Long> contents)
   {
      this.user_status = user_status;
      this.cart = cart;
      this.operation_type = operation_type;
      this.buy_equals_pay = buy_equals_pay;
      this.shipping_status = shipping_status;
      this.open_claim = open_claim;
      this.me = me;
      this.site = site;
      this.contents = contents;
   }

}